from __future__ import annotations

from pathlib import Path
from typing import Any, Protocol


class ServingAdapter(Protocol):
    def register_view(self, relation_name: str, parquet_path: Path) -> list[dict[str, Any]]: ...
    def drop_view(self, relation_name: str) -> None: ...
    def view_exists(self, relation_name: str) -> bool: ...
    def preview(self, relation_name: str, limit: int) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]: ...
